# -*- coding: utf-8 -*-
"""7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LLddP6fysV1btELgOJdSvybEkczr6TBK
"""

import streamlit as st
import yfinance as yf
import pandas_ta as ta
import twstock
import pandas as pd
import time
import plotly.graph_objects as go
from gnews import GNews

# 設定頁面與標題
st.set_page_config(page_title="AI 台股監控戰情室", layout="wide")

# --- 核心數據抓取函數 ---
@st.cache_data(ttl=3600)
def fetch_stock_data(stock_list):
    if not stock_list: return {}
    tickers = [s.strip() + ".TW" if "." not in s else s.strip() for s in stock_list]
    try:
        data = yf.download(tickers, period="1mo", interval="1d", auto_adjust=True, progress=False, threads=True)
        lookup = {}
        for sid in stock_list:
            t_id = sid.strip() + ".TW" if "." not in sid else sid.strip()
            try:
                df = data.xs(t_id, axis=1, level=1).dropna() if len(tickers) > 1 else data.dropna()
                if not df.empty and len(df) >= 14:
                    atr = ta.atr(df['High'], df['Low'], df['Close'], length=14)
                    lookup[sid.strip()] = {'atr': round(float(atr.iloc[-1]), 2), 'last': df['Close'].iloc[-1]}
            except: continue
        return lookup
    except: return {}

# --- 主介面 ---
st.title("📡 AI 台股大數據監控中心")
watch_in = st.text_input("👉 在此輸入台股代號 (多檔請用逗號隔開)", value="2330, 2317, 2454", key="main_input")
watch_list = [s.strip() for s in watch_in.split(',') if s.strip()]

if st.button("⚡ 啟動同步數據"):
    st.session_state.base = fetch_stock_data(watch_list)
    if st.session_state.base:
        st.success(f"✅ 已成功載入 {len(st.session_state.base)} 檔數據！")

# 分頁顯示功能
tab1, tab2, tab3 = st.tabs(["🔥 即時監控", "🌍 AI 風險分析", "📈 指標視覺化"])

with tab1:
    if 'base' in st.session_state:
        placeholder = st.empty()
        while True:
            try:
                rt = twstock.realtime.get(watch_list)
                rows = []
                for sid in watch_list:
                    if sid in st.session_state.base:
                        real = rt.get(sid)['realtime']
                        op = float(real['open']) if real['open'] != '-' else st.session_state.base[sid]['last']
                        cp = float(real['latest_trade_price']) if real['latest_trade_price'] != '-' else op
                        atr = st.session_state.base[sid]['atr']
                        rows.append({"代號": sid, "目前價": cp, "壓力位": round(op+atr*0.8, 2), "支撐位": round(op-atr*0.8, 2)})
                if rows: placeholder.table(pd.DataFrame(rows))
            except: pass
            time.sleep(15)
    else:
        st.info("請點擊上方「啟動同步數據」。")

with tab2:
    if st.button("🔍 掃描新聞"):
        gn = GNews(language='zh-TW', period='24h', max_results=2)
        for sid in watch_list:
            st.write(f"**【{sid}】新聞：**")
            try:
                for n in gn.get_news(f"{sid} 股票"): st.caption(n['title'])
            except: st.write("無新聞。")

with tab3:
    if 'base' in st.session_state:
        for sid, val in st.session_state.base.items():
            fig = go.Figure(go.Indicator(mode="gauge+number", value=val['last'], title={'text':f"{sid} 位階"}))
            st.plotly_chart(fig)